FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /django

# Copy entire project context into container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r backend/requirements.txt

EXPOSE 8000

CMD ["sh", "-c", "python backend/manage.py makemigrations core && python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"]